#!/usr/bin/env python3
"""Turns the files EKA2L1 expects to find beside itself into C++ tables.

Two sets of them. The patch libraries replace ROM routines that the emulator
would rather implement itself - most importantly the screen driver, which is
what carries a direct screen access game's pixels to the compositor. The
shaders are what the graphics driver draws with: without them every draw is a
silent no-op and the screen stays black.

Upstream ships both as files in folders and opens them by path. This machine
has no folders: it carries them inside its own binary instead, and every build
reads the same files in the same order, so the tables are the same bytes every
time.
"""

import os
import sys

def emit(out, prefix, files):
    for index, (_, path) in enumerate(files):
        with open(path, "rb") as handle:
            data = handle.read()
        out.append("    static const unsigned char %s_%d[] = {" % (prefix, index))
        out.append(",".join(str(b) for b in data))
        out.append("};\n")

    out.append("\n    const embedded_file %sS[] = {\n" % prefix)
    for index, (name, _) in enumerate(files):
        out.append('        { "%s", %s_%d, sizeof(%s_%d) },\n' % (name, prefix, index, prefix, index))
    out.append("    };\n\n")
    out.append("    const unsigned int %s_COUNT = %d;\n\n" % (prefix, len(files)))


def main():
    patch_root, shader_dir, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

    patch_files = []
    for group in sorted(os.listdir(patch_root)):
        group_dir = os.path.join(patch_root, group, "group")
        if not os.path.isdir(group_dir):
            continue
        for name in sorted(os.listdir(group_dir)):
            if name.endswith(".map") or name.endswith(".dll"):
                patch_files.append((name, os.path.join(group_dir, name)))

    patch_files.sort()

    shader_files = sorted((name, os.path.join(shader_dir, name))
        for name in os.listdir(shader_dir))

    out = []
    out.append("// Generated by waterbox/gen-embedded-files.py. Do not edit.\n")
    out.append('#include "embedded-files.h"\n\n')
    out.append("namespace chimera {\n")

    emit(out, "PATCH_BLOB", patch_files)
    emit(out, "SHADER_BLOB", shader_files)

    out.append("}\n")

    text = "".join(out)

    # Only write when the content changes, so a rebuild does not recompile a
    # quarter of a megabyte of tables for nothing.
    if os.path.exists(out_path):
        with open(out_path, "r") as handle:
            if handle.read() == text:
                return

    with open(out_path, "w") as handle:
        handle.write(text)

main()
